import { SiteHeader } from '@/components/site-header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteHeader />
        {children}
        <p className="p-7">
          Inspired by <a href="https://ui.shadcn.com/examples/music"><code>https://ui.shadcn.com/examples/music</code></a>
        </p>
      </body>
    </html>
  )
}
